"""
This is a setup.py script generated by py2applet and modified for Silta.

Usage:
    python3 setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = [
    ('silta/data', ['silta/data/logitech_devices.json']),
]
OPTIONS = {
    'argv_emulation': True,
    # 'iconfile': 'docs/icon.icns',
    'plist': {
        'CFBundleName': 'Silta',
        'CFBundleDisplayName': 'Silta',
        'CFBundleIdentifier': 'app.savanavenn.silta',
        'CFBundleVersion': '0.1.0',
        'CFBundleShortVersionString': '0.1.0',
        'NSHumanReadableCopyright': 'Copyright © 2025 Savanavenn. All rights reserved.',
        'LSUIElement': True,  # Agent app (menubar), set False if standard Dock app
        'NSAppleEventsUsageDescription': 'Silta needs to control your mouse and keyboard to share input between devices.',
        'NSBluetoothAlwaysUsageDescription': 'Silta needs Bluetooth access to switch Logitech devices between hosts.',
    },
    'packages': ['silta', 'rumps', 'pynput', 'pyautogui', 'objc', 'zeroconf'],
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
)
